/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package virtual.pet.shelter;
import java.util.Scanner;

public class App {
    public static void main(String[] args) {
        Scanner scanner = new Scanner(System.in);
        
        int adminChoice;

            ShelterClass shelter = new ShelterClass();

                shelter.inTakePets("Baxter", 10, 15, 20);
                shelter.inTakePets("Chance", 10, 10, 10);
                shelter.inTakePets("Oliver", 15, 20, 15);

            System.out.println("\nWelcome to the Pet Shelter!");
            shelter.allPetInfo();

    do {

        //! Display Menu
        menu();
        adminChoice = Integer.parseInt(scanner.nextLine());

        switch (adminChoice) {
            case 1:
                shelter.feedAllPets();
                System.out.println("Pets have been Fed! ");
                break;
            case 2:
                shelter.waterAllPets();
                System.out.println("Pets now have Water! ");
                break;
            case 3:
                playWithPet(shelter);
                break;
            case 4:
                shelter.adaptPets();
                break;
            case 5:
                shelter.assesNewPet();
                break;
            case 6:
                System.out.println( "Have a Great Night! See you tomorrow! ");
                break;
            default:
                    System.out.print("Please enter a valid selection: 1 = Feed, 2 = Water, 3 = Play, 4 = Adopt, 5 = Admit, 6 = Clock out");
                break;
        }
        shelter.allPetInfo();
            } while (adminChoice != 6);

            scanner.close();  
    }

        //! Method for the Menu
        public static void menu(){
        System.out.println("\nWhat would you like to do?");
        System.out.println("Enter 1 to Feed the Pets");
        System.out.println("Enter 2 to Hydrate the Pets");
        System.out.println("Enter 3 to Play with a Pet");
        System.out.println("Enter 4 Adopt a Pet");
        System.out.println("Enter 5 to Admit a New Pet");
        System.out.println("Enter 6 to Clock out of the Shelter");
        }

        //! Method for Playing
        public static void playWithPet(ShelterClass shelter){
            Scanner scanner = new Scanner(System.in);
            shelter.allPetNames();
            System.out.print("Enter Pet you wanna Play with: ");
            String petName = scanner.nextLine();
            shelter.playPet(petName);            
            System.out.println("\n" + petName + " Had a blast!\n");
        }


    }




